/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.frame;

import control.controlador.Control;
import control.controlador.baseDeDatos;
import control.entidades.Notificable;

/**
 * @author Claudio Espinoza
 */
public class Admin extends javax.swing.JFrame implements Notificable{

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void metodoEliminar() {

        String rut=jTextField_enterRut.getText(); // este se cambia por el de abajo es para que no tire error
        //rut = TEXTO DONDE UNO ESCRIBE EL RUT QUE VA A ELIMINAR

        if (!baseDeDatos.comprobarRutExistente(rut)) {
            baseDeDatos.eliminarCuenta(rut);
            String numtarjeta = baseDeDatos.retornarNumTarjeta(rut);
            baseDeDatos.eliminarTarjeta(numtarjeta);

        } else {
            mostrarProcesoFallido("Rut invalido");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_containerAdministrador = new javax.swing.JPanel();
        jPanel_containerBarLateral = new javax.swing.JPanel();
        jLabel_iconoUsuario = new javax.swing.JLabel();
        jLabel_tituloUsuario = new javax.swing.JLabel();
        jPanel_containerBtnVolver = new javax.swing.JPanel();
        jLabel_textoBtnSalir = new javax.swing.JLabel();
        jPanel_containerOpcion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_enterRut = new javax.swing.JTextField();
        jPanel_btnBorrar = new javax.swing.JPanel();
        jLabel_textBtnBorrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel_containerAdministrador.setBackground(new java.awt.Color(240, 241, 242));

        jPanel_containerBarLateral.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_iconoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Usuario.png"))); // NOI18N

        jLabel_tituloUsuario.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_tituloUsuario.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel_tituloUsuario.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_tituloUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_tituloUsuario.setText("Administrador");

        jPanel_containerBtnVolver.setBackground(new java.awt.Color(51, 51, 51));

        jLabel_textoBtnSalir.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_textoBtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_textoBtnSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_textoBtnSalir.setText("Volver");
        jLabel_textoBtnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_textoBtnSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_containerBtnVolverLayout = new javax.swing.GroupLayout(jPanel_containerBtnVolver);
        jPanel_containerBtnVolver.setLayout(jPanel_containerBtnVolverLayout);
        jPanel_containerBtnVolverLayout.setHorizontalGroup(
            jPanel_containerBtnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_textoBtnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_containerBtnVolverLayout.setVerticalGroup(
            jPanel_containerBtnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_containerBtnVolverLayout.createSequentialGroup()
                .addComponent(jLabel_textoBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_containerBarLateralLayout = new javax.swing.GroupLayout(jPanel_containerBarLateral);
        jPanel_containerBarLateral.setLayout(jPanel_containerBarLateralLayout);
        jPanel_containerBarLateralLayout.setHorizontalGroup(
            jPanel_containerBarLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_containerBarLateralLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_iconoUsuario))
            .addGroup(jPanel_containerBarLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_containerBarLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_tituloUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_containerBtnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_containerBarLateralLayout.setVerticalGroup(
            jPanel_containerBarLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_containerBarLateralLayout.createSequentialGroup()
                .addComponent(jLabel_iconoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_tituloUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(jPanel_containerBtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_containerOpcion.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Rut de usuario");

        jTextField_enterRut.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jTextField_enterRut.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_enterRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_enterRutActionPerformed(evt);
            }
        });

        jPanel_btnBorrar.setBackground(new java.awt.Color(51, 51, 51));

        jLabel_textBtnBorrar.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel_textBtnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_textBtnBorrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_textBtnBorrar.setText("Borrar");
        jLabel_textBtnBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_textBtnBorrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_btnBorrarLayout = new javax.swing.GroupLayout(jPanel_btnBorrar);
        jPanel_btnBorrar.setLayout(jPanel_btnBorrarLayout);
        jPanel_btnBorrarLayout.setHorizontalGroup(
            jPanel_btnBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_btnBorrarLayout.createSequentialGroup()
                .addComponent(jLabel_textBtnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_btnBorrarLayout.setVerticalGroup(
            jPanel_btnBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_btnBorrarLayout.createSequentialGroup()
                .addComponent(jLabel_textBtnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_containerOpcionLayout = new javax.swing.GroupLayout(jPanel_containerOpcion);
        jPanel_containerOpcion.setLayout(jPanel_containerOpcionLayout);
        jPanel_containerOpcionLayout.setHorizontalGroup(
            jPanel_containerOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_containerOpcionLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel_containerOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_containerOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel_btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_enterRut, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPanel_containerOpcionLayout.setVerticalGroup(
            jPanel_containerOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_containerOpcionLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_enterRut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_containerAdministradorLayout = new javax.swing.GroupLayout(jPanel_containerAdministrador);
        jPanel_containerAdministrador.setLayout(jPanel_containerAdministradorLayout);
        jPanel_containerAdministradorLayout.setHorizontalGroup(
            jPanel_containerAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_containerAdministradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_containerOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_containerBarLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_containerAdministradorLayout.setVerticalGroup(
            jPanel_containerAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_containerAdministradorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_containerAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel_containerOpcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_containerBarLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel_containerAdministrador, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2_borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_borrarMouseClicked

    }//GEN-LAST:event_jLabel2_borrarMouseClicked

    private void veAAAAAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_veAAAAAMouseClicked

    }//GEN-LAST:event_veAAAAAMouseClicked

    private void jPanel_funcionalidadBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_funcionalidadBorrarMouseClicked
       
    }//GEN-LAST:event_jPanel_funcionalidadBorrarMouseClicked

    private void jTextField_enterRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_enterRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_enterRutActionPerformed

    private void jLabel_textoBtnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_textoBtnSalirMouseClicked
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jLabel_textoBtnSalirMouseClicked

    private void jLabel_textBtnBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_textBtnBorrarMouseClicked
       metodoEliminar();
    }//GEN-LAST:event_jLabel_textBtnBorrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_iconoUsuario;
    private javax.swing.JLabel jLabel_textBtnBorrar;
    private javax.swing.JLabel jLabel_textoBtnSalir;
    private javax.swing.JLabel jLabel_tituloUsuario;
    private javax.swing.JPanel jPanel_btnBorrar;
    private javax.swing.JPanel jPanel_containerAdministrador;
    private javax.swing.JPanel jPanel_containerBarLateral;
    private javax.swing.JPanel jPanel_containerBtnVolver;
    private javax.swing.JPanel jPanel_containerOpcion;
    private javax.swing.JTextField jTextField_enterRut;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarProcesoFallido(String error) {
        NotificacionFail a=new NotificacionFail(error);
    }
}
