/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.frame;

import control.controlador.baseDeDatos;
import control.controlador.Control;
import control.entidades.Notificable;
import control.entidades.Tarjeta;
import control.entidades.Transaccion;
import control.entidades.Usuario;

import javax.swing.JOptionPane;

/*
 * @author Claudio Espinoza
 */
public class Registro extends javax.swing.JFrame implements Notificable {


    static final String DB_URL = "jdbc:mysql://localhost/clientes";
    static final String USER = "TestUser1";
    static final String PASS = "12345";


    /**
     * Creates new form Acceso
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLabel_tittle1 = new javax.swing.JLabel();
        JLabel_tittle = new javax.swing.JLabel();
        JSeparate_1 = new javax.swing.JSeparator();
        JField_rutEnter = new javax.swing.JTextField();
        JLabel_tittle4 = new javax.swing.JLabel();
        JSeparate_2 = new javax.swing.JSeparator();
        JField_pinEnter = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2_botonRegistro = new javax.swing.JPanel();
        JLabel_registrarse = new javax.swing.JLabel();
        JSeparate_3 = new javax.swing.JSeparator();
        JField_primerNombre = new javax.swing.JTextField();
        JLabel_tittle3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JSeparate_4 = new javax.swing.JSeparator();
        JField_mail = new javax.swing.JTextField();
        JLabel_tittle5 = new javax.swing.JLabel();
        JSeparate_5 = new javax.swing.JSeparator();
        JField_apellidoPaterno = new javax.swing.JTextField();
        JSeparate_6 = new javax.swing.JSeparator();
        JField_apellidoMaterno = new javax.swing.JTextField();
        JLabel_tittle6 = new javax.swing.JLabel();
        JLabel_tittle7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        JLabel_tittle1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        JLabel_tittle1.setForeground(new java.awt.Color(51, 51, 51));
        JLabel_tittle1.setText("BIENVENIDO A ");
        JLabel_tittle1.setAlignmentY(0.0F);

        JLabel_tittle.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        JLabel_tittle.setForeground(new java.awt.Color(51, 51, 51));
        JLabel_tittle.setText("Usuario (Rut)");

        JSeparate_1.setForeground(new java.awt.Color(0, 0, 0));

        JField_rutEnter.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        JField_rutEnter.setForeground(new java.awt.Color(102, 102, 102));
        JField_rutEnter.setBorder(null);
        JField_rutEnter.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        JField_rutEnter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JField_rutEnterMousePressed(evt);
            }
        });

        JLabel_tittle4.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        JLabel_tittle4.setForeground(new java.awt.Color(51, 51, 51));
        JLabel_tittle4.setText("Pin");

        JSeparate_2.setForeground(new java.awt.Color(0, 0, 0));

        JField_pinEnter.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        JField_pinEnter.setForeground(new java.awt.Color(102, 102, 102));
        JField_pinEnter.setBorder(null);
        JField_pinEnter.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        JField_pinEnter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JField_pinEnterMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jPanel2_botonRegistro.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2_botonRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2_botonRegistroMouseClicked(evt);
            }
        });

        JLabel_registrarse.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        JLabel_registrarse.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_registrarse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_registrarse.setText("Registrar");

        javax.swing.GroupLayout jPanel2_botonRegistroLayout = new javax.swing.GroupLayout(jPanel2_botonRegistro);
        jPanel2_botonRegistro.setLayout(jPanel2_botonRegistroLayout);
        jPanel2_botonRegistroLayout.setHorizontalGroup(
                jPanel2_botonRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 134, Short.MAX_VALUE)
                        .addGroup(jPanel2_botonRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JLabel_registrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
        );
        jPanel2_botonRegistroLayout.setVerticalGroup(
                jPanel2_botonRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 44, Short.MAX_VALUE)
                        .addGroup(jPanel2_botonRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2_botonRegistroLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(JLabel_registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 18, Short.MAX_VALUE)
                                        .addContainerGap()))
        );

        JSeparate_3.setForeground(new java.awt.Color(0, 0, 0));

        JField_primerNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        JField_primerNombre.setForeground(new java.awt.Color(102, 102, 102));
        JField_primerNombre.setBorder(null);
        JField_primerNombre.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        JField_primerNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JField_primerNombreMousePressed(evt);
            }
        });

        JLabel_tittle3.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        JLabel_tittle3.setForeground(new java.awt.Color(51, 51, 51));
        JLabel_tittle3.setText("Primer Nombre");

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("REGISTRO");
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setAutoscrolls(true);

        JSeparate_4.setForeground(new java.awt.Color(0, 0, 0));

        JField_mail.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        JField_mail.setForeground(new java.awt.Color(102, 102, 102));
        JField_mail.setBorder(null);
        JField_mail.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        JField_mail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JField_mailMousePressed(evt);
            }
        });

        JLabel_tittle5.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        JLabel_tittle5.setForeground(new java.awt.Color(51, 51, 51));
        JLabel_tittle5.setText("Correo");

        JSeparate_5.setForeground(new java.awt.Color(0, 0, 0));

        JField_apellidoPaterno.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        JField_apellidoPaterno.setForeground(new java.awt.Color(102, 102, 102));
        JField_apellidoPaterno.setBorder(null);
        JField_apellidoPaterno.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        JField_apellidoPaterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JField_apellidoPaternoMousePressed(evt);
            }
        });

        JSeparate_6.setForeground(new java.awt.Color(0, 0, 0));

        JField_apellidoMaterno.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        JField_apellidoMaterno.setForeground(new java.awt.Color(102, 102, 102));
        JField_apellidoMaterno.setBorder(null);
        JField_apellidoMaterno.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        JField_apellidoMaterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JField_apellidoMaternoMousePressed(evt);
            }
        });

        JLabel_tittle6.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        JLabel_tittle6.setForeground(new java.awt.Color(51, 51, 51));
        JLabel_tittle6.setText("Apellido Paterno");

        JLabel_tittle7.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        JLabel_tittle7.setForeground(new java.awt.Color(51, 51, 51));
        JLabel_tittle7.setText("Apellido Materno");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(52, 52, 52)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(JLabel_tittle1)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jLabel2))
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(JSeparate_1)
                                                                                        .addComponent(JField_rutEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(JLabel_tittle, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(JLabel_tittle4, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                        .addComponent(JSeparate_2, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(JField_pinEnter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(JSeparate_3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(JField_primerNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addComponent(JLabel_tittle3))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(JSeparate_5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(JField_apellidoPaterno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addComponent(JLabel_tittle6))
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(JLabel_tittle7)
                                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(JSeparate_6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(JField_apellidoMaterno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(JLabel_tittle5, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                .addComponent(JSeparate_4, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(JField_mail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(jPanel2_botonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(0, 46, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(JLabel_tittle1)
                                                        .addComponent(jLabel2))))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(JLabel_tittle3)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(JLabel_tittle6)
                                                .addComponent(JLabel_tittle7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(JField_primerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(JSeparate_3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(JField_apellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(JSeparate_5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(JField_apellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JSeparate_6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(JLabel_tittle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JField_rutEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(JSeparate_1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JLabel_tittle4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JField_pinEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(JSeparate_2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JLabel_tittle5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JField_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(JSeparate_4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2_botonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JField_rutEnterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JField_rutEnterMousePressed

    }//GEN-LAST:event_JField_rutEnterMousePressed

    private void JField_pinEnterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JField_pinEnterMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JField_pinEnterMousePressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanel2_botonRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2_botonRegistroMouseClicked
        Control control = new Control();

        String nombre = JField_primerNombre.getText();
        String apellido1 = JField_apellidoPaterno.getText();
        String apellido2 = JField_apellidoMaterno.getText();
        String rut = JField_rutEnter.getText();
        String pin = JField_pinEnter.getText();
        String email = JField_mail.getText();


        if (control.validarPin(pin)
                && control.isNumeric(pin)
                && control.validarRut(rut)
                && control.validarCorreo(email)
                && baseDeDatos.comprobarRutExistente(rut)
                && control.comprobarEscrituraRut(rut)) {


            String numTarjeta = control.generarNumeroTarjeta();

            baseDeDatos.agregarTarjeta(new Tarjeta(numTarjeta));
            baseDeDatos.agregarUsuario(new Usuario(nombre, apellido1, apellido2, rut, pin, email, numTarjeta));

            this.dispose();
            Login menu = new Login();
            menu.setVisible(true);

        } else {
            mostrarProcesoFallido("Esos valores no son valido");
        }

    }//GEN-LAST:event_jPanel2_botonRegistroMouseClicked

    private void JField_primerNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JField_primerNombreMousePressed

    }//GEN-LAST:event_JField_primerNombreMousePressed

    private void JField_mailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JField_mailMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JField_mailMousePressed

    private void JField_apellidoPaternoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JField_apellidoPaternoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JField_apellidoPaternoMousePressed

    private void JField_apellidoMaternoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JField_apellidoMaternoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JField_apellidoMaternoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JField_apellidoMaterno;
    private javax.swing.JTextField JField_apellidoPaterno;
    private javax.swing.JTextField JField_mail;
    private javax.swing.JTextField JField_pinEnter;
    private javax.swing.JTextField JField_primerNombre;
    private javax.swing.JTextField JField_rutEnter;
    private javax.swing.JLabel JLabel_registrarse;
    private javax.swing.JLabel JLabel_tittle;
    private javax.swing.JLabel JLabel_tittle1;
    private javax.swing.JLabel JLabel_tittle3;
    private javax.swing.JLabel JLabel_tittle4;
    private javax.swing.JLabel JLabel_tittle5;
    private javax.swing.JLabel JLabel_tittle6;
    private javax.swing.JLabel JLabel_tittle7;
    private javax.swing.JSeparator JSeparate_1;
    private javax.swing.JSeparator JSeparate_2;
    private javax.swing.JSeparator JSeparate_3;
    private javax.swing.JSeparator JSeparate_4;
    private javax.swing.JSeparator JSeparate_5;
    private javax.swing.JSeparator JSeparate_6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2_botonRegistro;
    // End of variables declaration//GEN-END:variables


    @Override
    public void mostrarProcesoFallido(String error) {
        NotificacionFail a = new NotificacionFail(error);
    }
}
